#
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: castell

development:
  <<: *default
  database: gcsystembd_dev

#test:
#  <<: *default
#  database: gcsystem_test

#production:
#  <<: *default
#  database: gcsystem_prod
